# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
default_platform(:ios)

platform :ios do
    sync_code_signing(
      type: "adhoc",
      app_identifier: "com.Wangushengshi.axd",
      team_id: "9XHK7Y3M6Z",
      username: "3336406072@qq.com",
      force: true,
    ) 
    build_app(
      scheme: "AixiangdaoDemo",
      configuration: "Debug",
      workspace:"AixiangdaoDemo.xcworkspace",
      silent: true,
      clean: true,
      output_directory: "dir",
      output_name: "Aixiangdao.ipa",
      export_method:"ad-hoc",
      include_bitcode: false
    )
  lane :sign do
    sync_code_signing(
      type: "adhoc",
      app_identifier: "com.Wangushengshi.axd",
      username: "3336406072@qq.com"
    )
  end
end
